# Documentation: http://goreleaser.com

# Build configuration
builds:
  - id: rss2md
    binary: rss2md
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64

# Archive configuration
archives:
  - id: myarchive
    builds:
      - rss2md
    format: zip
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md  # Ensure this matches the filename in your repository

# Release configuration
release:
  github:
    owner: msenturk
    name: rss2md
  prerelease: auto

# Snapshot configuration
snapshot:
  name_template: "{{ .Tag }}-next"

# Checksum and signing configuration
checksum:
  name_template: 'checksums.txt'
