# Documentation: http://goreleaser.com
builds:
  - id: rss2md
    binary: rss2md
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64

archives:
  - id: myarchive
    builds:
      - your_build_id
    format: zip
    format_overrides:
      - goos: windows
        format: zip
    files:
      - licence*
      - readme.md
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

release:
  github:
    owner: msenturk
    name: rss2md
  prerelease: auto

snapshot:
  name_template: "{{ .Tag }}-next"
