name: Release Go project

on:
  workflow_dispatch:

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5  # Update this to the Go version you want to use

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v0.200.0  # Use a specific version for stability
        with:
          version: latest
          args: release --clean  # Remove --snapshot for real releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
